/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'customerName' : string,
  'orderDate' : bigint,
  'productId' : string,
  'orderId' : string,
  'address' : string,
  'quantity' : bigint,
  'phone' : string,
}
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'originalPrice' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'benefits' : Array<string>,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface Review {
  'date' : bigint,
  'productId' : string,
  'comment' : string,
  'rating' : bigint,
  'reviewer' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[string, string, bigint, string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getReviewsByProduct' : ActorMethod<[string], Array<Review>>,
  'placeOrder' : ActorMethod<[Order], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];