/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'orderDate' : IDL.Int,
  'productId' : IDL.Text,
  'orderId' : IDL.Text,
  'address' : IDL.Text,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'date' : IDL.Int,
  'productId' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getReviewsByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'orderDate' : IDL.Int,
    'productId' : IDL.Text,
    'orderId' : IDL.Text,
    'address' : IDL.Text,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'date' : IDL.Int,
    'productId' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviewsByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'placeOrder' : IDL.Func([Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };